calculation/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.top,name='top'),
    path("keisan/",views.keisan,name='keisan'),
    path("shift/<int:workplace_id>/", views.shift, name="shift"), #シフトの詳細
    path("shift/<int:schedule_id>/remove/", views.shift_remove, name="shift_remove"), #シフトの削除
    path("registration/<int:workplace_id>/",views.registration, name='registration'),
    path("delete/<int:shift_id>/",views.delete, name='delete'),
    path("update/<int:shift_id>/",views.update, name='update'),
    path("test/",views.test),
    path("baito/",views.baito,name="baito"), #バイト先の登録
    path("baito/<int:workplace_id>/remove/", views.baito_remove, name="baito_remove")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('calculation.urls'))
]

calculation/models.py
import datetime
from django.db import models
from django.utils import timezone


class Workplsce(models.Model):
    """バイト先の情報"""
    name = models.CharField(max_length=50)
    wage = models.IntegerField(default=0)

class Schedule(models.Model):
    """スケジュール"""
    workplace = models.ForeignKey(Workplsce, on_delete=models.CASCADE)
    start_time = models.TimeField(default=datetime.time(7, 0, 0))
    end_time = models.TimeField( default=datetime.time(7, 0, 0))
    date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    def hours(self):
        end_minutes = self.end_time.hour*60 + self.end_time.minute
        start_minutes = self.start_time.hour*60 + self.start_time.minute
        end_minutes = end_minutes if (end_minutes >= start_minutes ) else end_minutes+24*60
        return (end_minutes - start_minutes) / 60

calculation/forms.py
import bootstrap_datepicker_plus as datetimepicker
from django import forms

from .models import Item

config/forms.py
from django import forms
from .models import Schedule


class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time

calculation/views.py
from django.shortcuts import render, redirect
from calculation.models import Schedule,Workplsce
import datetime

# Create your views here.
def top(request):
    """トップ画面(一覧画面)"""
    """日記一覧画面"""
    Workplsces = Workplsce.objects.all()
    context = {
        'workplsces' : Workplsces,
    }
    return render(request, 'calculation/top.html', context)

def shift(request, workplace_id):
    workplace_data = Workplsce.objects.get(pk=workplace_id)
    shifts = Schedule.objects.all().filter(workplace=workplace_data)
    salary_sum = 0
    for shift in shifts:
        salary_sum += workplace_data.wage * shift.hours()

    context = {
        'workplace_data' : workplace_data,
        'shifts' : shifts,
        'salary_sum':int(salary_sum),
    }
    return render(request, 'calculation/shift.html', context)

def shift_remove(request, schedule_id):
    terget_shift = Schedule.objects.get(pk=schedule_id)
    terget_shift.delete()
    return redirect('top')

def keisan(request):
    """一覧画面"""
    schedules = Schedule.objects.order_by("-date")
    res = []
    month_salary = 0
    total_time = 0
    for schedule in schedules:
        wage = schedule.workplace.wage # 時給
        time = schedule.hours()
        res.append({
            "workplace_name":schedule.workplace.name,
            "date":schedule.date,
            "starttime":schedule.start_time,
            "endtime":schedule.end_time,
            "time": time,
            "salary":int(wage*time),
            "id":schedule.id,
        })
        month_salary += int(wage*time)
        total_time += time
    context = {
        "context":res,
        "month_salary":month_salary,
        "total_time":total_time,
        }
    return render(request,'calculation/keisan.html', context)

def registration(request, workplace_id):
    """登録画面"""
    workplace_data = Workplsce.objects.get(pk=workplace_id)
    if request.method == 'POST':
        time = Schedule.objects.create(
            workplace = workplace_data,
            start_time = request.POST['start_time'],
            end_time = request.POST['end_time'],
            date = request.POST['date']
        )
        return redirect('shift',workplace_id)
    else:
        context = {
            "workplace_data" : workplace_data,
        }
        return render(request, 'calculation/registration.html', context)

def test(request):
    """test"""
    return render(request,'calculation/baito.html')

def baito(request):
    """新規登録画面"""
    if request.method == 'POST':
        baito1 = Workplsce.objects.create(
            name = request.POST['baito_name'],
            wage = request.POST['wage']
        )
        return redirect('top')
    return render(request,'calculation/baito.html')

def baito_remove(request, workplace_id):
    workplace_data = Workplsce.objects.get(pk=workplace_id)
    workplace_data.delete()
    return redirect("top")

def wage(request):
    """給料計算"""
    

def delete(request, shift_id):
    """削除画面"""
    shift = Schedule.objects.get(pk=shift_id)
    shift.delete()
    return redirect('keisan')

def update(request, shift_id):
    """更新画面"""
    shift = Schedule.objects.get(pk=shift_id)
    if request.method == 'GET':
        context = {
            "shift":shift,
        }
        return render(request, 'calculation/update.html', context)

    elif request.method == 'POST':
        shift.start_time= request.POST['start_time']
        shift.end_time = request.POST['end_time']
        shift.save()
        return redirect('keisan')

config/views.py
import datetime
from django.shortcuts import redirect
from django.views import generic
from . import mixins
from .forms import BS4ScheduleForm
from .models import Schedule
...
...

class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'app/mycalendar.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('app:mycalendar', year=date.year, month=date.month, day=date.day)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('app:mycalendar', year=date.year, month=date.month, day=date.day)

calculation/templates/calculation/baito.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/top.css' %}">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>バイト登録</title>
    <!--バイトの名前と時給を登録する画面-->
</head>

<body>
    <p><a href="{% url 'top' %}">トップへ戻る</a></p>
    <form action="{% url 'baito' %}" method="POST">
    <div class="container">
        <div class="header">
            <div class="logo">
                バイト登録
            </div>
            <div class="func">
                <ul>
                    <a href="{% url 'baito' %}">
                        <li>新規登録</li>
                    </a>
                    <a href="{% url 'keisan' %}">
                        <li>給料計算</li>
                    </a>
                </ul>
            </div>
        </div>
        <br>
        <br>

        <div class="row mx-auto">
            <div class="col-12">
                <form action="{% url 'baito' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="baito_name">バイト名</label>
                        <input type="text" name="baito_name" class="form-control" id="baito_namee"
                            placeholder="例: サイゼリヤ">
                    </div>
                    <div class="form-group">
                        <label for="wage">時給</label>
                        <input type="number" name="wage" class="form-control" id="wage">
                    </div>
                    <button type="submit" class="btn btn-primary">登録する</button>
                </form>
            </div>
        </div>
        <a href="{% url 'top' %}">一覧へ</a>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

calculation/templates/calculation/hozon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="static/css/top.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    $( function() {
        $( "#datepicker" ).datepicker();
    } );
    </script>
    <script src="js/timedropper.js"></script>
    <link rel="stylesheet" type="text/css" href="js/timedropper.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
        <title>Document</title>
    <link rel="stylesheet" type="text/css" href="static/css/top.css">
    <title>Document</title>
</head>
<body>
    <p><a href="{% url 'top' %}">トップへ戻る</a></p>
        <div class="header">
            <div class="logo">
                シフト登録
            </div>
            <div class="func">
                <ul>
                    <a href="{% url 'baito' %}"><li>新規登録</li></a>
                    <a href="{% url 'keisan' %}"><li>給料計算</li></a>
                </ul>
            </div>
        </div>
    <form action="{% url 'registration' %}" method="POST">
        <div class="regtop">
            <p>日付: <input name="date" type="text" id="datepicker"></p>
            <script>
                $(function () {
                    // timedropper
                    $("#id_created_at").timeDropper({
                        format: "H:mm",
                        setCurrentTime: false,
                    });
                });
            </script>
            <p>開始時刻</p>
            <input name="start_time" type="text" id="alarm" />
            <script>$( "#alarm" ).timeDropper();</script>

            <script>
                $(function () {
                    // timedropper
                    $("#id_created_at").timeDropper({
                        format: "H:mm",
                        setCurrentTime: false,
                    });
                });
            </script>
            <p>終了時刻</p>
            <input name="finish_time" type="text" id="alarm2" />
            <script>$( "#alarm2" ).timeDropper();</script>
        </div>
        <a href="" class="btn view reg">登録</a>
    </form>
    </body>


    </html>

calculation/templates/calculation/keisan.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        
        <link rel="stylesheet" href="{% static 'css/top.css' %}">
        
       <title>
           詳細画面
       </title>
    </head>
    <body>
        <div class="container">
            <p><a href="{% url 'top' %}">トップへ戻る</a></p>
            <div class="header">
                <div class="logo">
                    給料計算
                </div>
                <div class="func">
                    <ul>
                        <a href="{% url 'baito' %}"><li>新規登録</li></a>
                    </ul>
                </div>
            </div>
            <div class="time">
                <h1>合計 {{total_time}}時間</h1>
            </div>
            <div class="money main">
                <p>+￥{{month_salary}}</p>
            </div>
            <hr class="sifuto">
            {% for i in context %}

            <h3>{{i.workplace_name}}</h3>
            <p>{{i.date.month}}/{{i.date.day}} {{ i.starttime|time:"H:i" }} - {{ i.endtime|time:"H:i" }} [{{i.time}}時間] </p>
            <div class="money">
                <p>+￥{{i.salary}}</p>
            </div>
            <div>
                <a href="{% url 'update' i.id %}" class="btn view keisan a">シフト編集</a>
                <a href="{% url 'delete' i.id %}" class="btn view keisan d">シフト削除</a>
            </div>
            <hr class="keisan-hr">
            {% endfor %}
            
            
            <hr>
        </div>
    </body>

</html>

calculation/templates/calculation/registration.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/top.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(function () {
            $("#datepicker").datepicker({ dateFormat: "yy-mm-dd", });
        });
    </script>

    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="static/css/top.css">
    <title>Document</title>


</head>

<body>
    <p><a href="{% url 'top' %}">トップへ戻る</a></p>
    <div class="container">
        <div class="header">
            <div class="logo">
                シフト登録
            </div>
            <div class="func">
                <ul>
                    <a href="{% url 'baito' %}">
                        <li>新規登録</li>
                    </a>
                    <a href="{% url 'keisan' %}">
                        <li>給料計算</li>
                    </a>
                </ul>
            </div>
        </div>

        <form action="{% url 'registration' workplace_data.id %}" method="POST">
        {% csrf_token %}
        <div class="regtop">

            
            <p>日付: <input name="date" type="text" id="datepicker"></p>
            <script>
                $(function () {
                    // timedropper
                    $("#id_created_at").timeDropper({
                        format: "H:mm",
                        setCurrentTime: false,
                    });
                });
            </script>
            <p>開始時刻: <input name="start_time" type="text" id="alarm" /></p>
            <script>$("#alarm").timeDropper();</script>

            <script>
                $(function () {
                    // timedropper
                    $("#id_created_at").timeDropper({
                        format: "H:mm",
                        setCurrentTime: false,
                    });
                });
            </script>
            <p>終了時刻: <input name="end_time" type="text" id="alarm2" /></p>
            <script>$("#alarm2").timeDropper();</script>
        </div>
        <input type="submit" class="btn btn-outline-info" value="登録する" />
        </form>
    </div>
</body>

</html>

calculation/templates/calculation/registrationcopy.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="static/css/top.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <script>
    $( function() {
        $( "#datepicker" ).datepicker();
    } );
    </script>
    
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
        <title>Document</title>
    <link rel="stylesheet" type="text/css" href="static/css/top.css">
    <title>Document</title>
    
    
</head>
<body>
    <p><a href="{% url 'top' %}">トップへ戻る</a></p>
    <div class="header">
        <div class="logo">
                シフト登録
        </div>
        <div class="func">
            <ul>
                <a href="{% url 'baito' %}"><li>新規登録</li></a>
                <a href="{% url 'keisan' %}"><li>給料計算</li></a>
            </ul>
        </div>
    </div>
    <form action="{% url 'registration' workplace_data.id %}" method="POST"    >
        {% csrf_token %}
        <div class="regtop">
            

            <p>日付: <input name="date" type="text" id="datepicker"></p>
            <script>
                $(function () {
                    // timedropper
                    $("#id_created_at").timeDropper({
                        format: "H:mm",
                        setCurrentTime: false,
                    });
                });
            </script>
            <p>開始時刻</p>
            <input name="start_time" type="text" id="alarm" />
            <script>$( "#alarm" ).timeDropper();</script>

            <script>
                $(function () {
                    // timedropper
                    $("#id_created_at").timeDropper({
                        format: "H:mm",
                        setCurrentTime: false,
                    });
                });
            </script>
            <p>終了時刻</p>
            <input name="end_time" type="text" id="alarm2" />
            <script>$( "#alarm2" ).timeDropper();</script>
        </div>
        <input type="submit" value="登録する"/>
    </form>
    </body>


    </html>

calculation/templates/calculation/shift.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/top.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{{ workplace_data.name }}のシフト一覧</title>
</head>

<body>
    <p><a href="{% url 'top' %}">トップへ戻る</a></p>
    <hr>
    <div class="container">
        <h1 class="shift">{{ workplace_data.name }}のシフト一覧</h1>
        <h3>時給 : {{ workplace_data.wage }}円</h3>
        <p><a href="{% url 'baito_remove'　workplace_data.id %}" class="btn btn-outline-danger">バイト先の削除</a></p>
        <hr>
        <p><a href="{% url 'registration' workplace_data.id %}" class="btn btn-outline-info">シフトの登録</a></p>
        <hr>

        {% for shift in shifts %}
        <div class="dayshift">
            <p>{{ shift.date }}</p>
            <p>{{ shift.start_time }} から {{ shift.end_time }}</p>
        </div>
        <p><a href="{% url 'shift_remove' shift.id %}" class="btn btn-outline-info">シフトの削除</a></p>
        <hr>
        {% empty %}
        <h2>シフトの登録はありません。</h2>
        {% endfor %}

        <div >
            <p class="kyuryo">{{ workplace_data.name }}の給料　{{salary_sum}}円</p>
        </div>

        
    </div>


    
    

</body>

</html>

calculation/templates/calculation/test.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
  <script src="js/timedropper.js"></script>
  <link rel="stylesheet" type="text/css" href="js/timedropper.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
</head>
<body>
 
<p>Date: <input type="text" id="datepicker"></p>

<script>
    $(function () {
        // timedropper
        $("#id_created_at").timeDropper({
            format: "H:mm",
            setCurrentTime: false,
        });
    });
</script>

<input type="text" id="alarm" />
<script>$( "#alarm" ).timeDropper();</script>


 
</body>
</html>

calculation/templates/calculation/top.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <title>給料計算</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/top.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>
    <div class="container">
        <div class="header">
            <div class="logo">
                バイト一覧
            </div>
            <div class="func">
                <ul>
                    <a href="{% url 'baito' %}">
                        <li>新規登録</li>
                    </a>
                    <a href="{% url 'keisan' %}">
                        <li>給料計算</li>
                    </a>
                </ul>
            </div>
        </div>


        {% for workplsce in workplsces %}
        <div class="top">
            <a href="{% url 'shift' workplsce.id %}" class="btn btn-outline-danger">{{ workplsce.name }}</a>
            <div class="text-right"><a href="{% url 'registration' workplsce.id %}" class="btn btn-outline-info ri">シフト登録</a></div>
        </div>
        {% endfor %}
    </div>

</body>

</html>

calculation/templates/calculation/update.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/top.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(function () {
            $("#datepicker").datepicker({ dateFormat: "yy-mm-dd", });
        });
    </script>

    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="static/css/top.css">
    <title>Document</title>


</head>

<body>
    <p><a href="{% url 'top' %}">トップへ戻る</a></p>
    <div class="header">
        <div class="logo">
            シフト編集
        </div>
        <div class="func">
            <ul>
                <a href="{% url 'baito' %}">
                    <li>新規登録</li>
                </a>
                <a href="{% url 'keisan' %}">
                    <li>給料計算</li>
                </a>
            </ul>
        </div>
    </div>

    <form action="{% url 'update' shift.id %}" method="POST">
    {% csrf_token %}
    <div class="regtop">


        <p>開始時刻</p>
        <input name="start_time" type="text" id="alarm" value="{{shift.start_time}}"/>
        <script>$("#alarm").timeDropper();</script>

        <script>
            $(function () {
                // timedropper
                $("#id_created_at").timeDropper({
                    format: "H:mm",
                    setCurrentTime: false,
                });
            });
        </script>
        <p>終了時刻</p>
        <input name="end_time" type="text" id="alarm2" value="{{shift.end_time}}"/>
        <script>$("#alarm2").timeDropper();</script>
    </div>
    <input type="submit" value="変更する" />
    </form>
</body>

</html>